"""Add subscribers model and user updates

Revision ID: 82847e247ea8
Revises: 
Create Date: 2025-05-10 22:00:35.293790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82847e247ea8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar a tabela de assinantes (subscribers)
    op.create_table('subscribers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('clinic_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('document', sa.String(), nullable=True),
        sa.Column('zip_code', sa.String(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('number', sa.String(), nullable=True),
        sa.Column('city', sa.String(), nullable=True),
        sa.Column('state', sa.String(), nullable=True),
        sa.Column('segment_id', sa.UUID(), nullable=True),
        sa.Column('plan_id', sa.UUID(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
        sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_document'), 'subscribers', ['document'], unique=True)
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    
    # Adicionar subscriber_id na tabela de usuários
    op.add_column('users', sa.Column('subscriber_id', sa.UUID(), nullable=True))
    op.drop_index('ix_users_id', table_name='users')
    op.create_foreign_key(None, 'users', 'subscribers', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover subscriber_id da tabela de usuários
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'subscriber_id')
    
    # Remover a tabela de assinantes
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_document'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
